config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/nice-co/deployments/1234/postgresql/databases')

  scope '/:account_slug/deployments/:deployment_id' do
    namespace :postgresql do
      resources :databases, param: :name, only: [:index] do
        resources :tables, only: [:index]
      end
    end
  end

end

app/models/account.rb
class Account
  include Virtus.model

  attribute :id, Integer
  attribute :slug, String

  def self.find(id)
    new JSON.parse(Faraday.get("#{ENV['API_URL']}/accounts/#{id}").body)
  end

end

app/models/deployment.rb
class Deployment
  include Virtus.model

  attribute :type, String
  attribute :account_id, Integer
  attribute :name, Integer

  attribute :port, Integer
  attribute :host, String

  attribute :username, String
  attribute :password, String

  def self.find(id)
    response = Faraday.get("#{ENV['API_URL']}/deployments/#{id}")
    body = JSON.parse(response.body)
    class_by_type(body['type']).new(body)
  end

  def self.class_by_type(type)
    "#{type.classify}::Deployment".constantize
  end

end

app/models/postgresql/database.rb
class PostgreSQL::Database
  include Virtus.model

  attribute :deployment, PostgreSQL::Deployment
  attribute :name, String
  attribute :size, Integer

  def client
    deployment.client(name)
  end

  def tables
    client.exec(<<-eos
      SELECT 
        nspname AS schemaname,relname,reltuples
      FROM pg_class C
      LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
      WHERE 
        nspname NOT IN ('pg_catalog', 'information_schema') AND
        relkind='r' 
      ORDER BY reltuples DESC;
    eos
    ).map do |row|
      PostgreSQL::Table.new(name: row['relname'], rows_count: row['reltuples'], database: self, deployment: deployment)
    end
  end

end

app/models/postgresql/deployment.rb
class PostgreSQL::Deployment < Deployment
  
  def client(db_name = 'postgres')
    PG::Connection.new({
      host: host,
      port: port,
      user: username,
      password: password,
      dbname: db_name
    })
  end

  def databases
    client.exec(<<-eos
      SELECT pg_database.datname
      FROM pg_database
      WHERE datistemplate = false;
    eos
    ).select {|row| row['datname'] != 'postgres'}.map do |row|
      PostgreSQL::Database.new(name: row['datname'], deployment: self)
    end
  end

end

app/models/postgresql/table.rb
class PostgreSQL::Table
  include Virtus.model

  attribute :database, PostgreSQL::Database
  attribute :deployment, PostgreSQL::Deployment

  attribute :name, String

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :create_fake_session

  helper_method :current_account, :current_deployment

  private

  def current_deployment
    @current_deployment ||= Deployment.find(params[:deployment_id])
  end

  def current_account
    @current_account ||= Account.find(session[:account_id])
  end

  def create_fake_session
    session[:account_id] = 1337
  end

end

app/controllers/deployments_controller.rb
class DeploymentsController < ApplicationController
  
end

app/controllers/postgresql/base_controller.rb
class PostgreSQL::BaseController < ApplicationController

  helper_method :current_database

  def current_database
    return nil unless params[:database_name]
    PostgreSQL::Database.new(name: params[:database_name] || params[:name], deployment: current_deployment)
  end

end

app/controllers/postgresql/databases_controller.rb
class PostgreSQL::DatabasesController < PostgreSQL::BaseController

  def index
    render locals: {databases: current_deployment.databases}
  end

  def current_database
    return nil unless params[:name]
    PostgreSQL::Database.new(name: params[:name], deployment: current_deployment)
  end

end

app/controllers/postgresql/tables_controller.rb
class PostgreSQL::TablesController < PostgreSQL::BaseController

  def index
    render locals: {tables: current_database.tables}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.slim
- primary_nav do |nav|
  = nav.item 'Deployments', "/",
    icon: 'deployments',
    class: 'here'

app/views/layouts/application.html.slim
= render partial: 'layouts/nav'

= megatron_layout custom_nav: true
  - javascripts
    = javascript_include_tag "application", "data-turbolinks-track" => true

app/views/postgresql/databases/_header.slim
- page_header
  h2
    - breadcrumbs do |b|
      = b.crumb current_deployment.name, postgresql_databases_path
      = b.crumb current_database.name, postgresql_database_tables_path

app/views/postgresql/databases/_nav.slim
- secondary_nav do |nav|
  = nav.item 'Tables', postgresql_database_tables_path,
    icon: 'collections'

app/views/postgresql/databases/index.html.slim
= render partial: 'postgresql/deployments/header'
= render partial: 'postgresql/deployments/nav'

- main_header 'Databases'

- main
  .wide
    .box-table
      - databases.each do |database|
        .table-row
          .table-cell
            = link_to database.name, postgresql_database_tables_path(database_name: database.name)

app/views/postgresql/deployments/_header.slim
- page_header current_deployment.name

app/views/postgresql/deployments/_nav.slim
- secondary_nav do |nav|
  = nav.item 'Databases', postgresql_databases_path,
    icon: 'databases'

app/views/postgresql/tables/index.html.slim
= render partial: 'postgresql/databases/header'
= render partial: 'postgresql/databases/nav'

- main_header 'Tables'

- main
  .wide
    .box-table
      .table-head
        .table-row
          .table-cell name
      - tables.each do |table|
        .table-row
          .table-cell = table.name